# Preface {.unnumbered}

These lecture notes are for a very short course---roughly twelve 75-minute lectures---on international macroeconomics that I have taught to junior and senior undergraduates. Although no prior knowledge of economics is assumed, students typically come to the course after completing courses on introductory microeconomics and macroeconomics. 

This course is the second half of a one-semester course on international economics, with the first half on international trade. The course's textbook is @krugman2022international. My goal here is simply to present a concise version of chapters 13 through 18 of that book.

I had to grapple with some tough trade-offs because of the severe time constraint. The core of the course is the theoretical framework originally proposed by Robert A. Mundell\index{Mundell, Robert A.} and J. Marcus Fleming\index{Fleming, J. Marcus}. I assume perfect capital mobility\index{perfect capital mobility} throughout and, thereby, avoid all discussion of wealth effects and portfolio theory.^[On these issues, see @rodseth2000open. By perfect capital mobility\index{perfect capital mobility} I mean a world in which (a) people who buy assets care only about the expected returns of those assets, and (b) they all have the same expectations about future changes in exchange rates. See section XXX.] I also assume a "small" country and, thereby, avoid the complex interactions of two-country models. The perfect capital mobility and small country assumptions keep this course very similar to the undergraduate macroeconomics course that most of my students would have also taken. This simplicity, I think, allows students to focus on the special aspects of *international* macroeconomics without having to learn a new kind of macroeconomics.

However, the discussion of expectations here may surprise even students who have taken intermediate macroeconomics courses. I have broken up the discussion of short-run analysis into separate chapters on  permanent and temporary changes in exogenous variables. Expectations are assumed to be anchored to the long-run equilibrium outcome. This assumption is at the root of the need to distinguish between temporary and permanent changes in, say, fiscal policy. A temporary change affects neither the long-run equilibrium outcome nor people's expectations, which are, after all, assumed to be tied to the long-run equilibrium outcome. On the other hand, a permanent change in, say, government spending affects the long-run equilibrium level of the future value of the exchange rate and, consequently, people's expectations about the future value of the exchange rate. This change in expectations has short-run ramifications that are absent in the analysis of temporary changes in government spending.

These notions are present in @krugman2022international, but are not developed in a way that is clear enough and leisurely enough for most students to grasp.^[On page 442 of @krugman2022international the authors address the issue as follows: "A permanent policy shift affects not only the current value of the government's policy instrument (the money supply, government spending, or taxes) but also the *long-run* exchange rate. This in turn affects expectations about future exchange rates. Because these changes in expectations have a major influence on the exchange rate prevailing in the short run, the effects of permanent policy shifts differ from those of temporary shifts."] Other international macroeconomics textbooks are no better in this respect, and usually a lot worse.^[Consider @feenstra2008international. On page 551 of their excellent textbook, the authors write, "[W]e can form expectations of the future exchange rate using the long-run monetary approach ..." This easy-to-miss mention of the idea that expectations are based on the long-run equilibrium outcome is not adequately developed, as far as I am concerned. And the consequent need to distinguish between temporary and permanent policy changes is not as clearly developed as I would like.]

The role of the long-run outcome in anchoring expectations is also my reason to discuss the long run before the short run. It would be essentially impossible to do short-run analysis without some notion of how expectations are formed, and the formation of expectations would be impossible to explain without a discussion of long-run equilibrium.

These lecture notes are a work in progress. Please let me know if you see any errors or if you see a way to make the book better. My mailing address is Udayan Roy, College of Management, Long Island University, Brookville, NY 11548, USA. My email address is <udayan.roy@liu.edu>.
